services:
  app:
    image: hello_django:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
